# Column mapping
MAPPING_COLUMNS = {
    "Handelsname": "name",
    "Synonyme": "alias",
    "CAS-Nr": "cas_number",
    "Hersteller": "manufacturer",
    # "Konzentration [%]": "concentration",
    # "Dichte [g/cm\u00b3]": "density_gram_per_cubic_cm",
}

# Notes content
NOTE_COLUMNS = [
    "Piktogramme",
    "Reinheit",
    "Druck [Bar]",
    "max. Menge",
    "Konzentration [%]",
    "CMR",
    "H-Sätze",
    "EUH-Sätze",
    "P-Sätze",
]

# Product Category from openBIS
ALLOWED_PC_CODES = {
    "PC0",
    "PC1",
    "PC2",
    "PC3",
    "PC4",
    "PC7",
    "PC8",
    "PC9A",
    "PC9B",
    "PC9C",
    "PC11",
    "PC12",
    "PC13",
    "PC14",
    "PC15",
    "PC16",
    "PC17",
    "PC18",
    "PC20",
    "PC21",
    "PC23",
    "PC24",
    "PC25",
    "PC26",
    "PC27",
    "PC28",
    "PC29",
    "PC30",
    "PC31",
    "PC32",
    "PC33",
    "PC34",
    "PC35",
    "PC36",
    "PC37",
    "PC38",
    "PC39",
    "PC40",
    "PC41",
    "PC42",
}

# Division list
DIVISIONS = [
    "1.1 Inorganic Trace Analysis",
    "1.2 Biophotonics",
    "1.3 Instrumental Analytics",
    "1.4 Process Analytical Technology",
    "1.5 Protein Analysis",
    "1.6 Inorganic Reference Materials",
    "1.7 Organic Trace and Food Analysis",
    "1.8 Environmental Analysis",
    "1.9 Chemical and Optical Sensing",
    "2.1 Safety of Energy Carriers",
    "2.2 Process Simulation",
    "2.3 Classification of Hazardous Substances and Dangerous Goods",
    "2.4 Testing and Evaluation of Explosives and Pyrotechnics",
    "2.5 Conformity Assessment Explosives and Pyrotechnics",
    "3.1 Safety of Dangerous Goods Packagings and Batteries",
    "3.2 Safety of Energy Storage Systems",
    "3.3 Safety of Transport Containers",
    "3.4 Safety of Storage Containers",
    "3.5 Safety of Gas Storage Systems and Tanks For Dangerous Goods",
    "3.6 Electrochemical Energy Materials",
    "4.1 Biodeterioration and Reference Organisms",
    "4.2 Material-Microbiome Interactions",
    "4.3 Molecular and Applied Entomology",
    "4.4 Thermochemical Residues Treatment and Resource Recovery",
    "4.5 Analysis of Artefacts and Cultural Assets",
    "5.1 Microstructural Design and Degradation",
    "5.2 Metallic High-Temperature Materials",
    "5.3 Polymer Matrix Composites",
    "5.4 Advanced Multi-materials Processing",
    "5.5 Materials Modelling",
    "5.6 Glasses",
    "6.1 Surface and Thin Film Analysis",
    "6.2 Material and Surface Technologies",
    "6.3 Structure Analysis",
    "6.4 Materials Informatics",
    "6.5 Synthesis and Scattering of Nanostructured Materials",
    "6.6 Digital Materials Chemistry",
    "6.7 Materials Synthesis and Design",
    "7.1 Building Materials",
    "7.2 Buildings and Structures",
    "7.3 Fire Engineering",
    "7.4 Technology of Construction Materials",
    "7.5 Technical Properties of Polymeric Materials",
    "7.6 Corrosion and Corrosion Protection",
    "7.7 Modelling and Simulation",
    "8.1 Sensors, Measurement and Testing Methods",
    "8.2 Non-Destructive Testing Methods For Civil Engineering",
    "8.3 Thermographic Methods",
    "8.4 Acoustic and Electromagnetic Methods",
    "8.5 X-Ray Imaging",
    "8.6 Fibre Optic Sensors",
    "9.1 Components For Energy Carriers",
    "9.2 Testing Devices and Equipment",
    "9.3 Welding Technology",
    "9.4 Weld Mechanics",
    "9.5 Tribology and Wear Protection",
    "9.6 Additive Manufacturing of Metallic Components",
    "S.1 Quality In Testing",
    "S.2 Digitalization of Quality Infrastructure",
    "S.3 Ecodesign and Energy Labelling",
    "Z.1 Organisation, Controlling",
    "Z.2 Budget",
    "Z.3 Human Resources",
    "Z.4 Education and Training, Health Management",
    "Z.5 Procurement",
    "Z.6 Internal Services",
    "Z.7 Buildings",
    "Z.8 Legal Services office, Library",
    "Z.9 Research Services",
]
